config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'home/index'
  get 'home/about'
  get 'home/contect'
  get 'pstaffs/showuser'


  devise_scope :user do
  	delete 'sign_out', to: 'devise/sessions#new
'
  end
  devise_for :users
  resources :users



  
  resources :pstaffs
  get 'phase1/index'
  get 'phase1/phase1'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phase1.rb
class Phase1 < ApplicationRecord
end

app/models/pstaff.rb
class Pstaff < ApplicationRecord
	belongs_to :user
	has_attached_file :registration_certificate
    validates_attachment :registration_certificate, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
     
    

    has_attached_file :aadhaar_card
validates_attachment :aadhaar_card, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable,
   has_many :pstaffs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 private

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

    if current_user.admin == true


    elsif current_user.phase1 == true
       redirect_to phase1_phase1_path

    elsif current_user.phase2 == true

    elsif current_user.phase3 == true
      
    else
      @pstaff = current_user.pstaffs
      if @pstaff.ids.count == 0  

      else
        redirect_to pstaffs_path
      end
    end
	end

	def about
    end


   def contect
   end

   def home1
   	
   end
end

app/controllers/phase1_controller.rb
class Phase1Controller < ApplicationController
	def index
    end

    def phase1
    	
    	    @fetch=Pstaff.all
            
    end

    def phase2
            @fetch=Pstaff.all
    end


    def phase3
            @fetch=Pstaff.all
    	
    end

    def admin
         @fetch=Pstaff.all
    	
    end

end

app/controllers/pstaffs_controller.rb
class PstaffsController < ApplicationController
 before_action :set_pstaff, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!,expect: [:show,:index]
  # GET /pstaffs
  # GET /pstaffs.json
  def index
    @pstaffs = current_user.pstaffs
  end

  # GET /pstaffs/1
  # GET /pstaffs/1.json
  def show

     
  end
  #for user
  def showuser
    @pstaff = Pstaff.find(params[:id])
    
  end
  # GET /pstaffs/new
  

  def new
    @pstaff = current_user.pstaffs.build
  end

  # GET /pstaffs/1/edit
  def edit
  end

  # POST /pstaffs
  # POST /pstaffs.json
  def create
    @pstaff = current_user.pstaffs.build(pstaff_params)

    respond_to do |format|
      if @pstaff.save
        format.html { redirect_to @pstaff, notice: 'Pstaff was successfully created.' }
        format.json { render :user, status: :created, location: @pstaff }
      else
        format.html { render :new }
        format.json { render json: @pstaff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pstaffs/1
  # PATCH/PUT /pstaffs/1.json
  def update
    respond_to do |format|
      if @pstaff.update(pstaff_params)
        format.html { redirect_to @pstaff, notice: 'Pstaff was successfully updated.' }
        format.json { render :show, status: :ok, location: @pstaff }
      else
        format.html { render :edit }
        format.json { render json: @pstaff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pstaffs/1
  # DELETE /pstaffs/1.json
  def destroy
    @pstaff.destroy
    respond_to do |format|
      format.html { redirect_to pstaffs_url, notice: 'Pstaff was successfully destroyed.' }
      format.json { head :no_content }
    end
   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pstaff
      @pstaff = Pstaff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pstaff_params
      params.require(:pstaff).permit(:name, :gender, :mobile_no, :department, :address, :vehical_type, :registration_certificate, :aadhaar_card)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phase1_helper.rb
module Phase1Helper
end

app/views/home/about.html.erb
<h1> about us </h1>

app/views/home/contect.html.erb
<h1> contect us </h1>

app/views/home/home1.html.erb
<div class="jumbotron">
     NITK SURATHKAL
</div>

<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">Our Logo</a>
  <%= link_to "home",new_user_session_path %>
  <%= link_to "about",home_about_path %>
  <%= link_to "sign up",new_user_registration_path %>
  <%= link_to "sign in",new_user_session_path %>
  <%= link_to "contect us",home_contect_path %>
  
</nav>
<div class="conntainer">
	 <%= link_to "sign up",new_user_registration_path %>
      <%= link_to "sign in",new_user_session_path %>
     


</div>

app/views/home/index.html.erb
<div class="jumbotron">
     NITK SURATHKAL
</div>


  <%= current_user.email %>
 



<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">Our Logo</a>
  <%= link_to "home",home_index_path %>
  <%= link_to "about",home_about_path %>
  <%= link_to "sign up",new_user_registration_path %>
  <%= link_to "sign in",new_user_session_path %>
  <%= link_to "contact us",home_contect_path %>
  
</nav>


<!--
<div class="container">

<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul >
      <li ><%= link_to "sign up",new_user_registration_path %> </li>
      <li ><%= link_to "sign in",new_user_session_path %></li>
      <li><%= link_to "sign up",new_user_registration_path %></li>
    </ul>
  </div>
</nav>
</div>  -->
 <br>
 <br>
<div class="container ">
  <div class="container-fluid"> 
  <h3>  for parmanenet faculty           <%= link_to "apply",new_pstaff_path %></h3> 
  <h3>  for parmanenet faculty           <%= link_to "sign up",new_user_registration_path %></h3>
  <h3>  for parmanenet faculty           <%= link_to "sign up",new_user_registration_path %></h3>
  <h3>  for parmanenet faculty           <%= link_to "sign up",new_user_registration_path %></h3>
  <h3>  for parmanenet faculty           <%= link_to "sign up",new_user_registration_path %></h3>
  <h3>  for parmanenet faculty           <%= link_to "sign up",new_user_registration_path %></h3>
  <h3>  logout     <% if current_user %>
    <%= link_to "signout" , destroy_user_session_path ,method:     :delete  %>  <%end %></h3>
  
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"   %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
     

    <%= yield %>
  </body>
</html>

app/views/phase1/phase1.html.erb
<h1>
	<% @fetch.each do |r| %>
	<%=r.id%>
	<%end%>
</h1>

app/views/pstaffs/_form.html.erb
<%= bootstrap_form_with(model: pstaff, local: true) do |form| %>
  <% if pstaff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pstaff.errors.count, "error") %> prohibited this pstaff from being saved:</h2>

      <ul>
      <% pstaff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class ="jubotron text-center" >
      <h1 class="display-7">Permanent Staff</h1>
 </div>
 <div class="container_fluid" ">
  <div class="row" >
    <div class="col-sm-4">
    </div>
 <div class="col-sm-4" >
  <div class="shadow-lg p-3 mb-5 bg-black rounded">
  <div class="field" >
    <h5><%= form.text_field :name %></h5>
  </div>


  <div class="field">
    <h5><%= form.text_field :gender %></h5>
  </div>

  <div class="field">
   <h5><%= form.text_field :mobile_no %></h5>
  </div>

  <div class="field">
    <h5><%= form.text_field :department %></h5>
  </div>

  <div class="field">
   <h5><%= form.text_field :address %></h5>
  </div>

  <div class="field">
  <h5><%= form.text_field :vehical_type %></h5>
  </div>

  <div class="field">
  <h5><%= form.file_field :registration_certificate %></h5>
  </div>

  <div class="field">
   <h5><%= form.file_field :aadhaar_card %></h5>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class:"btn btn-primary" %>
    
  </div>
 </div>
</div>
</div> 
</div>


<% end %>

app/views/pstaffs/edit.html.erb
<div class="row">
<h1>Editing Pstaff</h1>
</div>

<%= render 'form', pstaff: @pstaff %>
<div class="row">
	<h1 class="align-left">
<%= link_to 'Show', @pstaff ,class:"btn btn-primary align-right" %> </h1>
<h1 class="align-right">
<%= link_to 'Back', pstaffs_path, class:"btn btn-primary align-left"  %></h1>
</div>

app/views/pstaffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pstaffs</h1>
 <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Mobile no</th>
      <th>Department</th>
      <th>Address</th>
      <th>Vehical type</th>
      <th>Registration certificate</th>
      <th>Aadhaar card</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pstaffs.each do |pstaff| %>
      <tr>
        <td><%= pstaff.name %></td>
        <td><%= pstaff.gender %></td>
        <td><%= pstaff.mobile_no %></td>
        <td><%= pstaff.department %></td>
        <td><%= pstaff.address %></td>
        <td><%= pstaff.vehical_type %></td>
        <td><%= pstaff.registration_certificate %></td>
        <td><%= pstaff.aadhaar_card %></td>

        <td><%= link_to 'Show', pstaff %></td>
        <% if current_user && current_user.admin %>
           current_user.redirect_to phase1_index_path 
        <td><%= link_to 'Edit', edit_pstaff_path(pstaff) %></td>
        <td><%= link_to 'Destroy', pstaff, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
        <% end %>
      </tr>

    <% end %>
  </tbody>
</table>
<br>
    <% if current_user %>
    <%= link_to "signout" , destroy_user_session_path ,method:     :delete  %>
    <% else %>
    <%= link_to "signin" , new_user_session_path %>
     <%= link_to "signin" , new_user_registration_path %>
     <% end %>
<%= link_to 'New Pstaff', new_pstaff_path %>

app/views/pstaffs/new.html.erb
<%= render 'form', pstaff: @pstaff %>

<%= link_to 'Back', pstaffs_path %>

app/views/pstaffs/show.html.erb
<h1> show </h1>


<p><%=current_user.id%></p>

<p><%=@pstaff.name%> </p> 
<% if current_user %>
    <%= link_to "signout" , destroy_user_session_path ,method:     :delete  %>
<% end %>

app/views/pstaffs/showuser.html.erb
<h1> showuser </h1>

 <p> <%= @pstaff.name %>